/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Asus
 */
public class ToggleButton extends javax.swing.JFrame {

    /**
     * Creates new form ToggleButton
     */
    public ToggleButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tbtnAgua = new javax.swing.JToggleButton();
        txtAlimentacion = new javax.swing.JTextField();
        tbtnLuz = new javax.swing.JToggleButton();
        tbtnRenta = new javax.swing.JToggleButton();
        LbAgua = new javax.swing.JLabel();
        LbLuz = new javax.swing.JLabel();
        LbRenta = new javax.swing.JLabel();
        btnTotal = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(null);

        jLabel1.setText("Alimentacion");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 70, 140, 40);

        tbtnAgua.setText("Agua");
        getContentPane().add(tbtnAgua);
        tbtnAgua.setBounds(130, 140, 111, 23);

        txtAlimentacion.setText("jTextField1");
        getContentPane().add(txtAlimentacion);
        txtAlimentacion.setBounds(250, 60, 290, 50);

        tbtnLuz.setText("Luz");
        tbtnLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnLuzActionPerformed(evt);
            }
        });
        getContentPane().add(tbtnLuz);
        tbtnLuz.setBounds(130, 210, 110, 23);

        tbtnRenta.setText("Renta");
        tbtnRenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnRentaActionPerformed(evt);
            }
        });
        getContentPane().add(tbtnRenta);
        tbtnRenta.setBounds(130, 270, 110, 23);

        LbAgua.setText("10");
        getContentPane().add(LbAgua);
        LbAgua.setBounds(380, 140, 80, 16);

        LbLuz.setText("7.80");
        getContentPane().add(LbLuz);
        LbLuz.setBounds(380, 210, 80, 16);

        LbRenta.setText("100");
        getContentPane().add(LbRenta);
        LbRenta.setBounds(380, 270, 90, 16);

        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });
        getContentPane().add(btnTotal);
        btnTotal.setBounds(270, 340, 72, 23);

        txtTotal.setEditable(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal);
        txtTotal.setBounds(150, 380, 510, 80);

        jLabel2.setText("CONSUMO DEL MES");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 26, 200, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void tbtnLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnLuzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnLuzActionPerformed

    private void tbtnRentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnRentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnRentaActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed


 double alimentacion,agua,renta,luz;
 
 alimentacion=Double.parseDouble(txtAlimentacion.getText());
 
 agua=Double.parseDouble(LbAgua.getText());
  renta=Double.parseDouble(LbRenta.getText());
 luz=Double.parseDouble(LbLuz.getText());

 double precioTotaL;
 
 precioTotaL=alimentacion;
        if (tbtnAgua.isSelected()) {
            precioTotaL=precioTotaL+agua;
        }
        if (tbtnLuz.isSelected()) {
            precioTotaL=precioTotaL+luz;
        }
  
        if (tbtnRenta.isSelected()) {
            precioTotaL=precioTotaL+renta;
        }       

        txtTotal.setText(precioTotaL+"$USD");
        
                
        
    }//GEN-LAST:event_btnTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToggleButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToggleButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToggleButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToggleButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToggleButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbAgua;
    private javax.swing.JLabel LbLuz;
    private javax.swing.JLabel LbRenta;
    private javax.swing.JButton btnTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton tbtnAgua;
    private javax.swing.JToggleButton tbtnLuz;
    private javax.swing.JToggleButton tbtnRenta;
    private javax.swing.JTextField txtAlimentacion;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
